language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm


before_script:
    - composer self-update
    - composer install

script:
    - ./build/tools/phpunit.phar --configuration ./build/travis-ci.xml

notifications:
  email: false
