<?php
/**
 * Part of the Laradic packages.
 * MIT License and copyright information bundled with this package in the LICENSE file.
 */
namespace Laradic\Config;

use Illuminate\Filesystem\Filesystem;

/**
 * Class Publisher
 *
 * @package     Laradic\Config
 * @author      Robin Radic
 * @license     MIT
 * @copyright   2011-2015, Robin Radic
 * @link        http://radic.mit-license.org
 */
class Publisher
{

    /**
     * The filesystem instance.
     *
     * @var \Illuminate\Filesystem\Filesystem
     */
    protected $files;

    /**
     * The configuration repository instance
     * @var \Laradic\Config\Repository
     */
    protected $config;

    /**
     * The output lines
     * @var array
     */
    protected $output = [];

    /**
     * Create a new publisher instance.
     *
     * @param  \Illuminate\Filesystem\Filesystem $files
     * @param  \Laradic\Config\Repository $config
     */
    public function __construct(Filesystem $files, Repository $config)
    {
        $this->files  = $files;
        $this->config = $config;
    }

    /**
     * Publish all packages that haven't been published yet
     * @return $this
     */
    public function publishAll()
    {
        foreach ($this->getPackages() as $package)
        {
            $this->publish($package);
        }

        return $this;
    }

    /**
     * Publish a package if it hasn't been published yet
     * @param $package
     * @return $this
     */
    public function publish($package)
    {
        if ( ! $this->isPublished($package) )
        {
            if ( ! $source = $this->getSourcePath($package) )
            {
                return $this;
            }

            $destination = $this->getDestinationPath($package);
            $this->ensureDestination($package);
            $this->files->copyDirectory($source, $destination);
            $this->output[] = "Published {$package}";
        }

        return $this;
    }

    /**
     * Get the output generated by the publish/publishAll methods
     * @return string
     */
    public function output()
    {
        return implode("\n", $this->output) . "\n";
    }

    /**
     * Create the destination directory if it doesnt already exist
     * @param $package
     */
    protected function ensureDestination($package)
    {
        $destination = $this->getDestinationPath($package);
        if ( ! $this->files->isDirectory($destination) )
        {
            $this->files->makeDirectory($destination, 0777, true);
        }
    }

    /**
     * Get the destination path to publish the package config files to
     * @param $package
     * @return string
     */
    protected function getDestinationPath($package)
    {
        return config_path('packages/' . $package);
    }

    /**
     * Check if the package already had it's config files published
     * @param $package
     * @return bool
     */
    protected function isPublished($package)
    {
        return $this->files->isDirectory($this->getDestinationPath($package));
    }

    /**
     * Get all packages that where created by using Laradic\Config\Traits\ConfigTrait
     * @return array
     */
    protected function getPackages()
    {
        $cbs = $this->config->getAfterLoadCallbacks();
        if ( empty($cbs) )
        {
            return [];
        }

        return array_keys($cbs);
    }

    /**
     * Resolve and get the directory path containing the configuration files for a package
     * @param $package
     * @return null|string
     */
    protected function getSourcePath($package)
    {
        // get package dir
        $packageDirs = [base_path($package), base_path('vendor/' . $package), base_path('packages/' . $package)];
        $packageDir  = null;
        foreach ($packageDirs as $dir)
        {
            if ( $this->files->isDirectory($dir) )
            {
                $packageDir = $dir;
                break;
            }
        }
        if ( $packageDir === null )
        {
            return $packageDir;
        }

        // get config dir
        $configDirs = ['config', 'resources/config'];
        $configDir  = null;
        foreach ($configDirs as $dir)
        {
            if ( $this->files->isDirectory($packageDir . '/' . $dir) )
            {
                $configDir = $packageDir . '/' . $dir;
                break;
            }
        }

        return $configDir;
    }
}